
import { UploaderInput, UploadResult, IModule } from '../types';
import { Buffer } from 'buffer';

/**
 * Phase 6: Uploader & Scheduler
 */
export class UploaderScheduler implements IModule<UploaderInput, UploadResult> {
  name = "Uploader & Scheduler";
  description = "Uploads video to YouTube via API and configures release schedule.";

  async execute(input: UploaderInput): Promise<UploadResult> {
    if (!input.video_asset || input.video_asset.status !== 'generated') {
      throw new Error("Invalid video asset.");
    }

    // 判斷是否為伺服器環境且具備憑證
    if (typeof window !== 'undefined' || !process.env.GOOGLE_CLIENT_ID || !input.authCredentials) {
      return this.uploadSimulated(input);
    }

    return this.uploadReal(input);
  }

  private async uploadReal(input: UploaderInput): Promise<UploadResult> {
    try {
      // 僅在伺服器端執行時動態載入巨大套件
      const { google } = await import('googleapis');
      const { Readable } = await import('stream');

      const oauth2Client = new google.auth.OAuth2(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET,
        process.env.GOOGLE_REDIRECT_URI
      );

      oauth2Client.setCredentials(input.authCredentials!);
      const service = google.youtube({ version: 'v3', auth: oauth2Client });

      // 支援 Data URL 或純 Base64
      const base64Data = input.video_asset.video_url.includes(';base64,') 
        ? input.video_asset.video_url.split(';base64,').pop() 
        : input.video_asset.video_url;

      if (!base64Data) throw new Error("影片數據解析失敗 (Invalid Video Data)");
      
      const buffer = Buffer.from(base64Data, 'base64');
      
      const stream = new Readable();
      stream.push(buffer);
      stream.push(null);

      const response = await service.videos.insert({
        part: ['snippet', 'status'],
        requestBody: {
          snippet: {
            title: input.metadata.title_template,
            description: input.metadata.description_template + "\n\nGenerated by AI Automation #Shorts",
            categoryId: '28' // Science & Technology
          },
          status: {
            privacyStatus: input.schedule.privacy_status || 'private',
            publishAt: input.schedule.publish_at
          }
        },
        media: {
          body: stream,
          mimeType: 'video/mp4'
        }
      });

      return {
        platform: 'youtube',
        video_id: response.data.id || 'unknown',
        platform_url: `https://youtube.com/shorts/${response.data.id}`,
        status: input.schedule.publish_at ? 'scheduled' : 'uploaded',
        scheduled_for: input.schedule.publish_at,
        uploaded_at: new Date().toISOString()
      };
    } catch (error: any) {
      console.error("[YouTube Upload Error]:", error);
      throw new Error(`YouTube API 上傳失敗: ${error.message}`);
    }
  }

  private async uploadSimulated(input: UploaderInput): Promise<UploadResult> {
    await new Promise(resolve => setTimeout(resolve, 1500));
    return {
      platform: 'youtube',
      video_id: "mock_vid_" + Math.random().toString(36).substr(2, 9),
      platform_url: "https://youtube.com/shorts/simulated",
      status: input.schedule.publish_at ? 'scheduled' : 'uploaded',
      scheduled_for: input.schedule.publish_at,
      uploaded_at: new Date().toISOString()
    };
  }
}
